// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzdidcxcefbkhsnukski.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6ZGlkY3hjZWZia2hzbnVrc2tpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA5MjQ2MTUsImV4cCI6MjA3NjUwMDYxNX0.6BypkXglpOJwk5xzF9ras0Y2tiOxneCCEnjSSXUL9y8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});